[I 2022-04-25 14:43:43.532 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-04-25 14:43:43.534 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-04-25 14:43:43.616 ServerApp] nbclassic | extension was successfully linked.
[I 2022-04-25 14:43:43.640 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-04-25 14:43:43.641 LabApp] JupyterLab extension loaded from /home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyterlab
[I 2022-04-25 14:43:43.641 LabApp] JupyterLab application directory is /home/martinm/nib_ckn/venv/share/jupyter/lab
[I 2022-04-25 14:43:43.643 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-04-25 14:43:43.643 ServerApp] Serving notebooks from local directory: /home/martinm/nib_ckn
[I 2022-04-25 14:43:43.643 ServerApp] Jupyter Server 1.11.2 is running at:
[I 2022-04-25 14:43:43.643 ServerApp] http://localhost:8889/lab
[I 2022-04-25 14:43:43.643 ServerApp]  or http://127.0.0.1:8889/lab
[I 2022-04-25 14:43:43.643 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-04-25 14:45:21.281 LabApp] Could not determine jupyterlab build status without nodejs
[I 2022-04-25 14:45:22.905 ServerApp] Kernel started: aa9c2b36-e3fe-4c2b-88d3-91ff76e1852c
[I 2022-04-25 14:47:44.843 ServerApp] Kernel restarted: aa9c2b36-e3fe-4c2b-88d3-91ff76e1852c
2022-04-25 14:47:49.606550: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-04-25 14:48:08.966 ServerApp] Creating new directory in /notebooks
[W 2022-04-25 14:48:15.535 ServerApp] delete /notebooks/Untitled Folder
[I 2022-04-25 14:49:04.021 ServerApp] New terminal with automatic name: 1
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-25 14:49:22.468 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 15:11:22.648 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 15:13:22.806 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 15:25:22.968 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:01:23.137 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:03:23.756 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:05:24.077 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:07:24.414 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[W 2022-04-25 16:09:20.353 ServerApp] Notebook notebooks/MPS_CKN-LinkPred_3_1.ipynb is not trusted
[I 2022-04-25 16:09:21.295 ServerApp] Kernel started: 77aaaf1d-c075-4e5e-9648-aea8a693a00d
[I 2022-04-25 16:09:25.160 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[W 2022-04-25 16:10:30.658 ServerApp] Notebook notebooks/CKN-LinkPred_4_1.ipynb is not trusted
[I 2022-04-25 16:10:31.554 ServerApp] Kernel started: cd078e93-ae5b-45fa-a577-cbc56f758b9e
[I 2022-04-25 16:12:31.932 ServerApp] Saving file at /notebooks/CKN-LinkPred_4_1.ipynb
[W 2022-04-25 16:12:31.933 ServerApp] Notebook notebooks/CKN-LinkPred_4_1.ipynb is not trusted
[I 2022-04-25 16:23:25.559 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:25:25.866 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:31:26.160 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:32:05.700 ServerApp] Copying notebooks/CKN-LinkPred_5_0.ipynb to /notebooks
[I 2022-04-25 16:32:20.108 ServerApp] Kernel started: 6c439cfd-703e-45d9-8a48-582745948072
[I 2022-04-25 16:33:26.487 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:34:20.776 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
2022-04-25 16:35:53.049082: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-04-25 16:36:22.658 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
[I 2022-04-25 16:38:22.989 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
[I 2022-04-25 16:41:28.603 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_0.ipynb
[I 2022-04-25 16:45:32.031 ServerApp] Saving file at /data/AtCKN_2022-01-26.tsv
[W 2022-04-25 16:45:45.153 ServerApp] delete /data/AtCKN_2022-01-26_fully-undirected.tsv.gz
[W 2022-04-25 16:45:45.172 ServerApp] delete /data/AtCKN_2022-01-26.tsv.gz
[I 2022-04-25 16:46:08.262 ServerApp] Saving file at /data/AtCKN_2022-01-26_fully-undirected.tsv
[I 2022-04-25 17:02:18.213 ServerApp] Kernel restarted: 6c439cfd-703e-45d9-8a48-582745948072
[I 2022-04-25 17:02:20.832 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:cec7849d-c939-43e6-b644-8162a543af62
[I 2022-04-25 17:02:20.843 ServerApp] Restoring connection for 6c439cfd-703e-45d9-8a48-582745948072:cec7849d-c939-43e6-b644-8162a543af62
[I 2022-04-25 17:02:23.204 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
2022-04-25 17:02:25.131656: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-04-25 17:04:24.464 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
[I 2022-04-25 17:05:47.557 ServerApp] Starting buffering for 77aaaf1d-c075-4e5e-9648-aea8a693a00d:9595c8b6-93b9-4d97-8e47-265fcdc62b88
[I 2022-04-25 17:05:50.388 ServerApp] Starting buffering for cd078e93-ae5b-45fa-a577-cbc56f758b9e:78ed5742-391a-4ab0-bbd2-ef304f2b636d
[I 2022-04-25 17:14:29.603 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:cec7849d-c939-43e6-b644-8162a543af62
Websocket closed
[I 2022-04-25 17:14:29.611 ServerApp] Starting buffering for aa9c2b36-e3fe-4c2b-88d3-91ff76e1852c:6f3851a6-f21b-44b4-bdce-1e9235192a9c
[I 2022-04-25 17:14:29.741 ServerApp] Restoring connection for 6c439cfd-703e-45d9-8a48-582745948072:cec7849d-c939-43e6-b644-8162a543af62
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-25 17:14:29.773 ServerApp] Restoring connection for aa9c2b36-e3fe-4c2b-88d3-91ff76e1852c:6f3851a6-f21b-44b4-bdce-1e9235192a9c
[W 2022-04-25 17:14:34.249 ServerApp] Nudge: attempt 10 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:14:39.260 ServerApp] Nudge: attempt 20 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:14:44.269 ServerApp] Nudge: attempt 30 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:14:49.277 ServerApp] Nudge: attempt 40 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:14:54.286 ServerApp] Nudge: attempt 50 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:14:59.294 ServerApp] Nudge: attempt 60 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:15:04.301 ServerApp] Nudge: attempt 70 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:15:09.309 ServerApp] Nudge: attempt 80 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:15:14.318 ServerApp] Nudge: attempt 90 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:15:19.325 ServerApp] Nudge: attempt 100 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:15:24.332 ServerApp] Nudge: attempt 110 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-25 17:15:29.342 ServerApp] Nudge: attempt 120 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[E 2022-04-25 17:15:29.741 ServerApp] Uncaught exception GET /api/kernels/6c439cfd-703e-45d9-8a48-582745948072/channels?session_id=cec7849d-c939-43e6-b644-8162a543af62 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:9001', method='GET', uri='/api/kernels/6c439cfd-703e-45d9-8a48-582745948072/channels?session_id=cec7849d-c939-43e6-b644-8162a543af62', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
      File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
        future.result()
    tornado.util.TimeoutError: Timeout
[W 2022-04-25 17:15:59.742 ServerApp] WebSocket ping timeout after 90001 ms.
[W 2022-04-25 17:15:59.757 ServerApp] WebSocket ping timeout after 90000 ms.
[W 2022-04-25 17:15:59.774 ServerApp] WebSocket ping timeout after 90000 ms.
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
[I 2022-04-25 17:16:04.775 ServerApp] Starting buffering for aa9c2b36-e3fe-4c2b-88d3-91ff76e1852c:6f3851a6-f21b-44b4-bdce-1e9235192a9c
[W 2022-04-25 17:16:51.762 ServerApp] Replacing stale connection: 6c439cfd-703e-45d9-8a48-582745948072:cec7849d-c939-43e6-b644-8162a543af62
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-25 17:16:52.085 ServerApp] Restoring connection for aa9c2b36-e3fe-4c2b-88d3-91ff76e1852c:6f3851a6-f21b-44b4-bdce-1e9235192a9c
[W 2022-04-25 17:18:22.067 ServerApp] WebSocket ping timeout after 90001 ms.
[W 2022-04-25 17:18:22.087 ServerApp] WebSocket ping timeout after 90001 ms.
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
[I 2022-04-25 17:18:27.088 ServerApp] Starting buffering for aa9c2b36-e3fe-4c2b-88d3-91ff76e1852c:6f3851a6-f21b-44b4-bdce-1e9235192a9c
[I 2022-04-25 17:32:52.180 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:cec7849d-c939-43e6-b644-8162a543af62
[W 2022-04-25 17:38:28.713 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.718 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.735 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.884 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.887 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.888 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.890 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.891 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.892 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.893 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.894 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.895 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.896 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.897 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.898 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.899 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.901 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.902 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.903 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.904 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.905 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.906 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.907 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.909 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.910 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.911 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.912 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.913 ServerApp] zmq message arrived on closed channel
[W 2022-04-25 17:38:28.914 ServerApp] zmq message arrived on closed channel
[I 2022-04-26 11:30:35.580 ServerApp] 302 GET / (127.0.0.1) 0.39ms
[W 2022-04-26 11:30:37.334 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[W 2022-04-26 11:33:09.848 ServerApp] WebSocket ping timeout after 119990 ms.
[I 2022-04-26 11:33:14.850 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:3ffd592b-5d48-4157-af12-34e63dadc381
[W 2022-04-26 11:33:37.757 ServerApp] WebSocket ping timeout after 119906 ms.
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
[I 2022-04-26 11:34:56.118 ServerApp] 302 GET / (127.0.0.1) 0.43ms
[W 2022-04-26 11:34:58.026 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-26 11:36:17.777 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:ee55ce4f-8c9a-4c28-9fc9-43a1e02cfab7
Websocket closed
[I 2022-04-26 12:21:54.623 ServerApp] 302 GET / (127.0.0.1) 0.43ms
[W 2022-04-26 12:21:56.202 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-26 12:22:29.414 ServerApp] Kernel restarted: 6c439cfd-703e-45d9-8a48-582745948072
[I 2022-04-26 12:22:32.031 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[I 2022-04-26 12:22:32.042 ServerApp] Restoring connection for 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
2022-04-26 12:22:36.390909: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-04-26 12:23:57.681 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
[I 2022-04-26 12:32:11.186 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
Websocket closed
[I 2022-04-26 12:32:11.217 ServerApp] Restoring connection for 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-26 12:58:20.883 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
[I 2022-04-26 13:00:21.101 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
[I 2022-04-26 13:08:21.440 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_1.ipynb
[I 2022-04-26 13:08:24.635 ServerApp] New terminal with automatic name: 2
TermSocket.open: 2
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 2
[I 2022-04-26 13:30:47.864 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
Websocket closed
Websocket closed
TermSocket.open: 2
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 2
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-26 13:30:47.922 ServerApp] Restoring connection for 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[W 2022-04-26 13:30:52.431 ServerApp] Nudge: attempt 10 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:30:57.440 ServerApp] Nudge: attempt 20 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:02.451 ServerApp] Nudge: attempt 30 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:07.462 ServerApp] Nudge: attempt 40 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:12.473 ServerApp] Nudge: attempt 50 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:17.483 ServerApp] Nudge: attempt 60 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:22.492 ServerApp] Nudge: attempt 70 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:27.501 ServerApp] Nudge: attempt 80 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:32.510 ServerApp] Nudge: attempt 90 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:37.520 ServerApp] Nudge: attempt 100 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:42.531 ServerApp] Nudge: attempt 110 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[W 2022-04-26 13:31:47.538 ServerApp] Nudge: attempt 120 on kernel 6c439cfd-703e-45d9-8a48-582745948072
[E 2022-04-26 13:31:47.923 ServerApp] Uncaught exception GET /api/kernels/6c439cfd-703e-45d9-8a48-582745948072/channels?session_id=ab02e11c-d02f-4689-8fc8-17f61028fc10 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:9001', method='GET', uri='/api/kernels/6c439cfd-703e-45d9-8a48-582745948072/channels?session_id=ab02e11c-d02f-4689-8fc8-17f61028fc10', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
      File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
        future.result()
    tornado.util.TimeoutError: Timeout
[W 2022-04-26 13:32:17.890 ServerApp] WebSocket ping timeout after 90001 ms.
[W 2022-04-26 13:32:17.905 ServerApp] WebSocket ping timeout after 90001 ms.
[W 2022-04-26 13:32:17.922 ServerApp] WebSocket ping timeout after 90000 ms.
Exception in callback BaseAsyncIOLoop._handle_events(36, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(36, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(36, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(36, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(36, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(36, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/martinm/nib_ckn/venv/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
Websocket closed
[W 2022-04-26 13:37:07.714 ServerApp] Replacing stale connection: 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
TermSocket.open: 2
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 2
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-04-26 13:41:07.706 ServerApp] Starting buffering for 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[W 2022-04-26 13:41:08.299 ServerApp] Replacing stale connection: 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[W 2022-04-26 13:45:08.436 ServerApp] Replacing stale connection: 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[W 2022-04-26 13:45:31.873 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:33.411 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:33.413 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:33.432 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:33.448 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:33.486 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:33.513 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:33.518 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:35.178 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:35.181 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:35.370 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:48.177 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.128 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.131 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.220 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.250 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.275 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.291 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.330 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.339 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.509 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:49.569 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:45:50.067 ServerApp] zmq message arrived on closed channel
[W 2022-04-26 13:49:10.656 ServerApp] Replacing stale connection: 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[W 2022-04-26 13:53:22.803 ServerApp] Replacing stale connection: 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[W 2022-04-26 13:57:37.587 ServerApp] Replacing stale connection: 6c439cfd-703e-45d9-8a48-582745948072:ab02e11c-d02f-4689-8fc8-17f61028fc10
[I 2022-05-06 10:32:50.278 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-05-06 10:32:50.279 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-05-06 10:32:50.363 ServerApp] nbclassic | extension was successfully linked.
[I 2022-05-06 10:32:50.386 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-05-06 10:32:50.386 LabApp] JupyterLab extension loaded from /home/martinm/nib_ckn/venv/lib/python3.8/site-packages/jupyterlab
[I 2022-05-06 10:32:50.386 LabApp] JupyterLab application directory is /home/martinm/nib_ckn/venv/share/jupyter/lab
[I 2022-05-06 10:32:50.388 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-05-06 10:32:50.388 ServerApp] Serving notebooks from local directory: /home/martinm/nib_ckn
[I 2022-05-06 10:32:50.388 ServerApp] Jupyter Server 1.11.2 is running at:
[I 2022-05-06 10:32:50.388 ServerApp] http://localhost:8889/lab
[I 2022-05-06 10:32:50.388 ServerApp]  or http://127.0.0.1:8889/lab
[I 2022-05-06 10:32:50.388 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-05-06 10:33:28.594 LabApp] Could not determine jupyterlab build status without nodejs
[W 2022-05-06 10:33:31.872 ServerApp] Notebook notebooks/CKN-LinkPred_5_3.ipynb is not trusted
[W 2022-05-06 10:33:31.979 ServerApp] Notebook notebooks/CKN-LinkPred_5_2.ipynb is not trusted
[W 2022-05-06 10:33:32.342 ServerApp] Notebook notebooks/CKN-LinkPred-GCN_1_0.ipynb is not trusted
[I 2022-05-06 10:33:36.699 ServerApp] Kernel started: db17d39d-a8a1-416a-bf2d-35f291ba0941
[I 2022-05-06 10:33:36.704 ServerApp] Kernel started: e9aa970e-4e2e-43d1-8505-91d12b8bbc3a
[I 2022-05-06 10:33:36.709 ServerApp] Kernel started: 22cb9088-ff57-4b06-8683-9bc24b4520ea
[I 2022-05-06 10:33:36.947 ServerApp] Kernel started: fe797c7a-c6f5-4b9d-a56a-a198786039b4
[I 2022-05-06 10:33:37.304 ServerApp] Kernel started: 8565f97b-4475-4ca8-b587-6b4f91e58f79
[I 2022-05-06 10:33:37.511 ServerApp] Kernel started: 0b194552-6bc5-44ee-9d3f-289d15cb1a54
[I 2022-05-06 10:33:45.978 ServerApp] Starting buffering for 0b194552-6bc5-44ee-9d3f-289d15cb1a54:6f86d8d4-c1b9-4400-b246-1d06a90ff99e
[I 2022-05-06 10:45:41.875 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_4.ipynb
[I 2022-05-06 10:47:41.132 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2.ipynb
2022-05-06 10:48:13.413985: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-05-06 10:49:44.802 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2.ipynb
[I 2022-05-06 10:51:46.123 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2.ipynb
[I 2022-05-06 10:53:42.676 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[I 2022-05-06 10:53:52.187 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2.ipynb
[I 2022-05-06 10:55:43.852 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[I 2022-05-06 10:55:53.708 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2.ipynb
[I 2022-05-06 10:57:44.438 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 10:57:44.439 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
2022-05-06 10:59:25.610588: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-05-06 10:59:44.807 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 10:59:44.807 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:01:45.357 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:01:45.358 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:03:18.445 ServerApp] New terminal with automatic name: 1
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 2022-05-06 11:04:14.275 ServerApp] Copying notebooks/CKN-LinkPred_3_2.ipynb to /notebooks
[I 2022-05-06 11:04:31.894 ServerApp] Kernel started: 647008f7-aa33-44dd-ade0-50cc70575078
[I 2022-05-06 11:06:15.413 ServerApp] Kernel restarted: 22cb9088-ff57-4b06-8683-9bc24b4520ea
[I 2022-05-06 11:06:19.165 ServerApp] Starting buffering for 22cb9088-ff57-4b06-8683-9bc24b4520ea:86fb94d3-d20d-4d24-b1be-a0fe6d50f6f1
[I 2022-05-06 11:06:19.508 ServerApp] Restoring connection for 22cb9088-ff57-4b06-8683-9bc24b4520ea:86fb94d3-d20d-4d24-b1be-a0fe6d50f6f1
2022-05-06 11:06:25.284638: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-05-06 11:06:32.049 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2-corrected.ipynb
[I 2022-05-06 11:07:12.485 ServerApp] Kernel restarted: 647008f7-aa33-44dd-ade0-50cc70575078
[I 2022-05-06 11:07:12.632 ServerApp] Starting buffering for 647008f7-aa33-44dd-ade0-50cc70575078:1866dd8a-fe15-4cc9-ae82-196a4d6731f2
[I 2022-05-06 11:07:12.638 ServerApp] Restoring connection for 647008f7-aa33-44dd-ade0-50cc70575078:1866dd8a-fe15-4cc9-ae82-196a4d6731f2
2022-05-06 11:07:17.186286: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-05-06 11:07:27.549 ServerApp] Kernel restarted: 22cb9088-ff57-4b06-8683-9bc24b4520ea
[I 2022-05-06 11:07:32.867 ServerApp] Starting buffering for 22cb9088-ff57-4b06-8683-9bc24b4520ea:86fb94d3-d20d-4d24-b1be-a0fe6d50f6f1
[I 2022-05-06 11:07:32.882 ServerApp] Restoring connection for 22cb9088-ff57-4b06-8683-9bc24b4520ea:86fb94d3-d20d-4d24-b1be-a0fe6d50f6f1
2022-05-06 11:07:37.849193: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[I 2022-05-06 11:07:54.073 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2.ipynb
[I 2022-05-06 11:08:32.318 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2-corrected.ipynb
[I 2022-05-06 11:09:38.997 ServerApp] Starting buffering for e9aa970e-4e2e-43d1-8505-91d12b8bbc3a:4a689411-d731-460f-874b-9ca10b16597b
[I 2022-05-06 11:09:45.555 ServerApp] Starting buffering for db17d39d-a8a1-416a-bf2d-35f291ba0941:4b249655-feec-4b96-adde-be4efbf3c4a0
[I 2022-05-06 11:11:46.456 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:11:46.457 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:15:46.810 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:15:46.810 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:17:47.251 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:17:47.251 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:19:47.528 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:19:47.529 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:21:48.288 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:21:48.289 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:23:48.707 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:23:48.708 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:25:49.212 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:25:49.213 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:26:32.925 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2-corrected.ipynb
[I 2022-05-06 11:27:50.043 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:27:50.043 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:27:54.370 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2.ipynb
[I 2022-05-06 11:28:33.469 ServerApp] Saving file at /notebooks/CKN-LinkPred_3_2-corrected.ipynb
[I 2022-05-06 11:29:50.659 ServerApp] Saving file at /notebooks/CKN-LinkPred_5_5.ipynb
[W 2022-05-06 11:29:50.660 ServerApp] Notebook notebooks/CKN-LinkPred_5_5.ipynb is not trusted
[I 2022-05-06 11:30:47.797 ServerApp] Creating new directory in /notebooks
[W 2022-05-06 11:31:47.925 ServerApp] Notebook notebooks/NetworkX_excs.ipynb is not trusted
[I 2022-05-06 11:31:49.752 ServerApp] Kernel started: d03a348f-5ac1-4e98-b92e-5e57062827ab
[I 2022-05-06 11:33:19.547 ServerApp] Starting buffering for d03a348f-5ac1-4e98-b92e-5e57062827ab:7a568d74-26ed-4a9b-a0ce-3b880f972268
[I 2022-05-06 11:34:57.370 ServerApp] Starting buffering for fe797c7a-c6f5-4b9d-a56a-a198786039b4:de5aa9b6-289b-476d-81e0-38466e5797a9
[I 2022-05-06 11:35:24.949 ServerApp] Kernel started: 61583383-730f-45ab-8624-336d68f5d3a2
[I 2022-05-06 11:40:57.863 ServerApp] New terminal with automatic name: 2
TermSocket.open: 2
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 2
